# Generated by Django 3.0 on 2020-02-16 10:26

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, unique=True)),
                ('code', models.TextField()),
                ('linenos', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('python', 'Python'), ('c#', 'C#'), ('java', 'Java')], default='python', max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'snippets',
                'ordering': ['created'],
            },
        ),
        migrations.AddIndex(
            model_name='snippet',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['id'], name='snippets_id_076cc2_brin'),
        ),
    ]
