# Generated by Django 3.0.3 on 2020-03-04 10:35

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20200226_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ['created'], 'verbose_name': 'Snippet', 'verbose_name_plural': 'Snippets'},
        ),
        migrations.AddIndex(
            model_name='snippet',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='snippets_title_da73d3_gin'),
        ),
    ]
